python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/baseline/baselines.py --nexp 1 --noPairs --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/baseline
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/baseline/baselines.py --nexp 1 --mixedPairs --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/baseline
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/baseline/baselines.py --nexp 1  --nomixedPairs --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/baseline
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/baseline/baselines.py --nexp 2  --mixedPairs --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/baseline
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/baseline/baselines.py --nexp 2 --nomixedPairs --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/baseline
