python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/baseline/baselines.py --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/baseline
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/baseline/baselines_2snap.py --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/baseline
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/baseline/baselines_nomix.py --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/baseline
