python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/AGN_DDF/agn_ddf.py --illum_limit 60  --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/AGN_DDF
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/alt_sched/alt_sched.py --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/alt_sched
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/alt_sched/alt_sched_large.py --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/alt_sched

python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/roll_alt/alt_roll.py --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/roll_alt
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/roll_alt/alt_wfd.py --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/roll_alt
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/roll_alt_dust/alt_roll_dust.py --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/roll_alt_dust
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/roll_alt_dust/alt_wfd_dust.py --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/roll_alt_dust
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/baseline/baselines.py --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/baseline
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/bulge/bulges.py --strat_name bs --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/bulge
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/bulge/bulges.py --strat_name bulge_wfd --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/bulge
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/bulge/bulges.py --strat_name i_heavy --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/bulge
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/bulge/bulge_cadence.py --strat_name bs --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/bulge
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/bulge/bulge_cadence.py --strat_name bulge_wfd --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/bulge
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/bulge/bulge_cadence.py --strat_name i_heavy --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/bulge
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/DCR/dcr.py --nham 1 --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/DCR
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/DCR/dcr.py --nham 2 --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/DCR
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/DCR/dcr.py --nham 3 --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/DCR
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/DESC_DDF/desc_ddf.py --illum_limit 60  --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/DESC_DDF
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/DESC_DDF/desc_ddf.py --illum_limit 30  --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/DESC_DDF
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/DESC_DDF/desc_ddf.py --illum_limit 15  --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/DESC_DDF
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/DESC_DDF/desc_ddf.py --illum_limit 10  --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/DESC_DDF
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/DESC_DDF/desc_ddf.py --illum_limit 7  --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/DESC_DDF
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/DESC_DDF/desc_ddf.py --illum_limit 5  --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/DESC_DDF
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/DESC_DDF/desc_ddf.py --illum_limit 4  --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/DESC_DDF
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/DESC_DDF/desc_ddf.py --illum_limit 3  --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/DESC_DDF
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/filter_load/filter_load.py --illum_limit 60  --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/filter_load
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/filter_load/filter_load.py --illum_limit 30  --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/filter_load
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/filter_load/filter_load.py --illum_limit 15  --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/filter_load
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/filter_load/filter_load.py --illum_limit 10  --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/filter_load
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/filter_load/filter_load.py --illum_limit 7  --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/filter_load
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/filter_load/filter_load.py --illum_limit 5  --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/filter_load
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/filter_load/filter_load.py --illum_limit 4  --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/filter_load
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/filter_load/filter_load.py --illum_limit 3  --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/filter_load
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/footprints/run_footprints.py --target_name big_sky --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/footprints
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/footprints/run_footprints.py --target_name gp_heavy --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/footprints
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/footprints/run_footprints.py --target_name baseline --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/footprints
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/footprints/run_footprints.py --target_name big_sky_nouiy --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/footprints
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/footprints/run_footprints.py --target_name newA --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/footprints
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/footprints/run_footprints.py --target_name newB --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/footprints
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/footprints/run_footprints.py --target_name bluer_footprint --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/footprints
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/footprints/run_footprints.py --target_name stuck_rolling --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/footprints
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/footprints/run_footprints.py --target_name big_sky_dust --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/footprints
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/footprints/run_footprints.py --target_name no_gp_north --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/footprints
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/footprints/run_footprints.py --target_name add_mag_clouds --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/footprints

python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/platform/baselines.py --survey_length 366 --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/platform
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/rolling_cadence/simple_rolling.py --splits 2 --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/rolling_cadence
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/rolling_cadence/simple_rolling.py --splits 3 --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/rolling_cadence
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/rolling_cadence/simple_rolling.py --splits 5 --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/rolling_cadence
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/rolling_cadence/simple_rolling.py --splits 10 --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/rolling_cadence
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/rolling_cadence/delayed_rolling.py --splits 2 --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/rolling_cadence
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/rolling_cadence/delayed_rolling.py --splits 3 --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/rolling_cadence
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/rolling_cadence/delayed_rolling.py --splits 6 --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/rolling_cadence
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/rolling_cadence/delayed_rolling.py --splits 2 --scale_down_factor 0.1 --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/rolling_cadence
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/rolling_cadence/delayed_rolling.py --splits 3 --scale_down_factor 0.1 --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/rolling_cadence
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/rolling_cadence/delayed_rolling.py --splits 6 --scale_down_factor 0.1 --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/rolling_cadence
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/templates/templates.py --template_weight 0. --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/templates
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/templates/templates.py --template_weight 0.1 --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/templates
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/templates/templates.py --template_weight 0.5 --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/templates
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/templates/templates.py --template_weight 1.0 --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/templates
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/templates/templates.py --template_weight 1.5 --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/templates
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/templates/templates.py --template_weight 2.0 --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/templates
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/templates/templates.py --template_weight 2.5 --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/templates
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/templates/templates.py --template_weight 3.0 --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/templates
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/templates/templates.py --template_weight 4.0 --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/templates
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/templates/templates.py --template_weight 5.0 --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/templates
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/templates/templates.py --template_weight 6.0 --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/templates
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/templates/templates.py --template_weight 8.0 --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/templates
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/templates/templates.py --template_weight 10.0 --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/templates
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/twilight_neo/twilight_neo.py --night_mod 1 --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/twilight_neo
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/twilight_neo/twilight_neo.py --night_mod 2 --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/twilight_neo
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/twilight_neo/twilight_neo.py --night_mod 3 --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/twilight_neo
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/twilight_neo/twilight_neo.py --night_mod 4 --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/twilight_neo
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/wfd_depth/wfd_footprints.py --target_name wfd_standard --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/wfd_depth
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/wfd_depth/wfd_footprints.py --target_name wfd_95 --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/wfd_depth
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/wfd_depth/wfd_footprints.py --target_name wfd_90 --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/wfd_depth
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/wfd_depth/wfd_footprints.py --target_name wfd_85 --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/wfd_depth
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/wfd_depth/wfd_footprints.py --target_name wfd_80 --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/wfd_depth
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/wfd_depth/wfd_footprints.py --target_name wfd_75 --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/wfd_depth
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/wfd_depth/wfd_footprints.py --target_name wfd_70 --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/wfd_depth
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/wfd_depth/wfd_footprints.py --target_name wfd_65 --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/wfd_depth
