python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/wfd_only/wfd_only.py --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/wfd_only
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/wfd_only/wfd_only_2snap.py --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/wfd_only
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/wfd_only/wfd_only_nomix.py --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/wfd_only
