python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/DCR/dcr.py --nham 1 --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/DCR
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/DCR/dcr.py --nham 2 --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/DCR
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/DCR/dcr.py --nham 3 --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs_1.3/DCR
